# Compose file that combines the reddit_ex image
# with a postgresql database container on a volume
# passing in all necessary secrets
#
# podman-compose --env-file .compose.env up -d
#

services:
  reddit:
    image: localhost/reddit_ex
    container_name: reddit
    restart: always
    networks:
      - reddit-network
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PHX_HOST: ${PHX_HOST}
      DATABASE_URL: ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql-reddit/${POSTGRES_DB}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REFRESH_TOKEN: ${GOOGLE_REFRESH_TOKEN}
    ports:
      - "${HOST_PORT}:4000"
    depends_on:
      - psql-reddit
  psql-reddit:
    image: docker.io/library/postgres
    container_name: psql-reddit
    restart: always
    networks:
      - reddit-network
    volumes:
      - psql-data-reddit:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
networks:
  reddit-network:
    name: reddit-network
volumes:
  psql-data-reddit:
    name: psql-data-reddit
